SELECT *
FROM MEMBER;

SELECT *
FROM MEMBER_DETAILS_TRG;

MERGE INTO MEMBER_DETAILS_TRG  TRG
USING MEMBER MS
ON (MS.MEMBER_ID=TRG.MEMBER_ID)
WHEN MATCHED THEN
UPDATE 
SET 
 TRG.MEMBER_NAME=MS.MEMBER_NAME,
 TRG.AGE=MS.AGE,
 TRG.GENDER=MS.GENDER,
 TRG.ADDRESS=MS.ADDRESS,
 TRG.MEMBERSHIP_START_DATE=MS.MEMBERSHIP_START_DATE,
 TRG.MEMBERSHIP_END_DATE=MS.MEMBERSHIP_END_DATE
WHEN NOT MATCHED THEN
INSERT (MEMBER_ID,MEMBER_NAME,AGE,GENDER,ADDRESS,MEMBERSHIP_START_DATE,MEMBERSHIP_END_DATE)
VALUES (MS.MEMBER_ID,
        MS.MEMBER_NAME,
        MS.AGE,
        MS.GENDER,
        MS.ADDRESS,
        MS.MEMBERSHIP_START_DATE,
        MS.MEMBERSHIP_END_DATE);


--INSERTING VALUES IN MEMBER.
SELECT *
FROM MEMBER;

INSERT INTO MEMBER
VALUES('M105','Tejaswi',20,'M','Hinjewadi','01-02-2023','01-05-2023');

UPDATE MEMBER
SET
ADDRESS='Kharadi,Pune'
WHERE MEMBER_ID='M105';
